language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:tmsz-kapela/valgrind-pmem
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev valgrind
  - cp src/test/testconfig.sh.example src/test/testconfig.sh
script: make -j cstyle && make EXTRA_CFLAGS=-DUSE_VALGRIND -j &&
        make EXTRA_CFLAGS=-DUSE_VALGRIND -j test && make check
